name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Rooster-AI/rooster-deepface.git@34702da59c85435e9ce1786bbd27fdf5fde3b822#egg=deepface
        pip install pylint
        pip install opencv-python
        pip install deepface
        pip install resend
        pip install supabase
        pip install python-dotenv

    - name: Build Docker image
      run: |
        docker build -t roosteradmin/serverimage:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push roosteradmin/serverimage:latest

    - name: Deploy to EC2
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-west-1
        aws ec2 run-instances --image-id ami-02d3fd86e6a2f5122 --instance-type inf1.xlarge --key-name rooster-server-1 --security-group-ids sg-09b7f528fc3ae2d4c sg-065c09b2c422fc947 --subnet-id subnet-045a43e6383bd6d41 --user-data '#!/bin/bash -ex\n
        docker pull roosteradmin/serverimage:latest
        docker run -d -p 5000:5000 --restart always roosteradmin/serverimage:latest