name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Rooster-AI/rooster-deepface.git@34702da59c85435e9ce1786bbd27fdf5fde3b822#egg=deepface
        pip install pylint
        pip install opencv-python
        pip install deepface
        pip install resend
    - name: Analysing the code with pylint
      run: |
        chmod +x .github/workflows/pylint_runner.sh
        ./.github/workflows/pylint_runner.sh
